(** FPan Floating-Point Operation Finder *)

open Cil_types

let print_stmt out = function
  | Instr i ->
    (match i with
    | Set _ -> Format.fprintf out "Hrm..."
    | Call _ -> Format.fprintf out "Not supported"
    | Local_init _ -> Format.fprintf out "???"
    | _ -> Printer.pp_instr out i)
  | Return _ -> Format.pp_print_string out "<return> "
  | Goto _ -> Format.pp_print_string out "<goto> "
  | Break _ -> Format.pp_print_string out "<break> "
  | Continue _ -> Format.pp_print_string out "<continue> "
  | If (e,_,_,_) -> Format.fprintf out "if %a" Printer.pp_exp e
  | Switch (e,_,_,_) -> Format.fprintf out "switch %a" Printer.pp_exp e
  | Loop _ -> Format.fprintf out "Should unroll loop"
  | Block _ -> Format.fprintf out "<block> "
  | UnspecifiedSequence _ -> Format.fprintf out "<unspecified sequence> "
  | TryFinally _ | TryExcept _ | TryCatch _ -> Format.fprintf out "<try> "
  | Throw _ -> Format.fprintf out "<throw> "
(* | _       -> Printer.pp_binop out PlusA (TFloat(FDouble,[])) *)

class find_flops out = object
  inherit Visitor.frama_c_inplace

  (* Visit file *)
  method! vfile _ =
    Format.fprintf out "// Automatically generated by fpan\n";
    Cil.DoChildrenPost (fun f -> Format.fprintf out "\n"; f)
  
  (* Global definitions *)
  method! vglob_aux g =
    match g with
    | GFun(f,_) ->
      Format.fprintf out "@[< hov 2> { {@ \
                          // function %a\n\
                          @[< hv 2> Variables\n@[< hv 2>; @]@]@ "
          Printer.pp_varinfo f.svar;
      Cil.DoChildrenPost(fun g -> Format.fprintf out "}@]@ "; g)
    (* Note: Function annotations are not global annotations;
       TODO: Figure out what _are_ global annotations anyway *)
    | GAnnot(a,l) ->
      Format.fprintf out "// Found global annotation %a, location %a"
          Printer.pp_global_annotation a
          Printer.pp_location l;
      Cil.DoChildrenPost(fun g -> Format.fprintf out "\n"; g)
    | _ -> Cil.SkipChildren
  
  (* Statement *)
  method! vstmt_aux s =
    Format.fprintf out "@[< hov 2> s%d@ [label=%S]@];@ "
      s.sid (Pretty_utils.to_string print_stmt s.skind);
    List.iter
      (fun succ -> Format.fprintf out "@[s%d -> s%d;@]@ " s.sid succ.sid)
      s.succs;
    Format.fprintf out "@]";
    Cil.DoChildren
end

