{
  description = "FPCC";

  inputs = {
    nixpkgs.url = "github:NixOS/nixpkgs/nixpkgs-unstable";

    flake-utils.url = "github:numtide/flake-utils";

    # Fetch kodiak and precisa as flake inputs instead of using the versions in
    # the git submodule. These are pinned to the same commits though. Update
    # these when the submodules update.
    kodiak-src = {
      url = "github:nasa/Kodiak/cb77f1bb68e7ae8c7466bf8cbf4fe95ad619489a";
      flake = false;
    };

    precisa-src = {
      url = "github:nasa/PRECiSA/a3c4805cfc4c0153b27c6168255445a69e0e04b2";
      flake = false;
    };
  };

  outputs =
    { self, nixpkgs, flake-utils, kodiak-src, precisa-src, ... }:
    flake-utils.lib.eachDefaultSystem (
      system:
      let
        # Kodiak is released under the NASA Open Source Agreement, which nixpkgs
        # classifies as "unfree". Allow kodiak here so we don't have to set
        # NIXPKGS_ALLOW_UNFREE manually.
        pkgs = import nixpkgs {
          inherit system;
          config.allowUnfreePredicate = pkg: builtins.elem (lib.getName pkg) [ "kodiak" ];
        };
        lib = nixpkgs.lib;
        # "`haskell.lib.compose` is preferred for any new code"
        # (see https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/haskell-modules/lib/default.nix#L10-L11).
        haskellLib = pkgs.haskell.lib.compose;

        haskellPkgs = pkgs.haskell.packages.ghc967.override {
          overrides = hself: hsuper: {
            th-abstraction = hself.callHackage "th-abstraction" "0.5.0.0" { };
            th-desugar = hself.callHackage "th-desugar" "1.15" { };
            singletons-th = hself.callHackage "singletons-th" "3.2" { };
          };
        };

        # Use the version of Haskell Language Server that matches GHC 9.6.7.
        haskell-language-server = pkgs.haskell.packages.ghc967.haskell-language-server;

        filib = pkgs.stdenv.mkDerivation {
          pname = "filib";
          version = "3.0.2";

          src = pkgs.fetchurl {
            url = "https://www2.math.uni-wuppertal.de/wrswt/software/filib++/filibsrc-3.0.2.tar.gz";
            sha256 = "14583ca412d0a081a176e115b452386fb7078bc590cf22af86db635fbf817562";
          };

          # Following setup.sh, build FILIB with the position-independent flag
          # and using the C++11 standard.
          CFLAGS = "-fPIC";
          CPPFLAGS = "-fPIC";
          CXXFLAGS = "-fPIC -std=c++11";

          enableParallelBuilding = true;

          meta = with lib; {
            description = "A fast interval library";
            homepage = "https://www2.math.uni-wuppertal.de/wrswt/software/filib.html";
            license = licenses.lgpl21Plus;
            platforms = platforms.unix;
          };
        };

        kodiak = pkgs.stdenv.mkDerivation {
          pname = "kodiak";
          version = "2.0.4";

          src = kodiak-src;

          nativeBuildInputs = [ pkgs.cmake pkgs.pkg-config ];
          buildInputs = [ filib ];

          # Consumed by Kodiak's CMake/FindFILIB.cmake
          # (see https://github.com/nasa/Kodiak/blob/master/CMake/FindFILIB.cmake#L18-L25).
          FILIB_ROOT = filib;

          enableParallelBuilding = true;

          meta = with lib; {
            description = "Library for rigorous verification of non-linear arithmetic";
            homepage = "https://github.com/nasa/Kodiak";
            license = licenses.nasa13;
            platforms = platforms.unix;
          };
        };

        # The cabal2nix tool turns precisa's `extra-libraries: kodiak` into a
        # `kodiak` function argument, so we pass our derivation here.
        precisa = lib.pipe (haskellPkgs.callCabal2nix "precisa" "${precisa-src}/PRECiSA" { inherit kodiak; }) [
          (haskellLib.addExtraLibraries [ filib ])
          # The version bounds in nixpkgs are too tight to fit GHC 9.6.7.
          haskellLib.doJailbreak
          haskellLib.dontCheck
        ];

        # FPCC.cabal is generated by hpack from package.yaml, so we generate it
        # from package.yaml here first. We restrict the source to just what
        # hpack and the build need, so that changes to other files
        # (e.g. flake.nix) don't unnecessarily invalidate the source.
        fpccSrc =
          let
            fs = lib.fileset;
            src = fs.toSource {
              root = ./.;
              fileset = fs.unions [
                ./package.yaml
                ./LICENSE
                ./README.md
                ./Setup.hs
                ./src
                ./app
                ./test
              ];
            };
          in
          pkgs.runCommand "fpcc-src" {
            nativeBuildInputs = [ pkgs.haskellPackages.hpack ];
          } ''
            cp -r ${src} $out
            chmod -R u+w $out
            cd $out
            hpack
          '';

        # FPCC shells out to `gcc` at runtime (through language-c), so it needs
        # `gcc` on PATH. Alias `gcc` to the stdenv C compiler.
        gccForLanguageC = pkgs.runCommand "gcc-for-language-c" { } ''
          mkdir -p $out/bin
          ln -s ${pkgs.stdenv.cc}/bin/cc $out/bin/gcc
        '';

        fpcc = lib.pipe (haskellPkgs.callCabal2nix "FPCC" fpccSrc { inherit precisa; }) [
          (haskellLib.addExtraLibraries [ kodiak filib ])
          # Potentially revisit
          haskellLib.dontHaddock
          haskellLib.dontCheck
          (haskellLib.overrideCabal (drv: {
            buildTools = (drv.buildTools or [ ]) ++ [ pkgs.makeWrapper ];
            postInstall = (drv.postInstall or "") + ''
              wrapProgram $out/bin/fpcc --prefix PATH : ${lib.makeBinPath [ gccForLanguageC ]}
            '';
          }))
        ];

        # Export a `stack` that uses the nix-provided GHC and the libraries we
        # configured.
        stackWithSystemGhc = pkgs.writeShellScriptBin "stack" ''
          exec ${pkgs.stack}/bin/stack \
            --system-ghc --no-install-ghc \
            --extra-lib-dirs=${kodiak}/lib \
            --extra-lib-dirs=${filib}/lib \
            --extra-include-dirs=${filib}/include \
            "$@"
        '';
      in
      {
        packages = {
          default = fpcc;
          fpcc = fpcc;
          precisa = precisa;
          kodiak = kodiak;
          filib = filib;
        };

        apps = {
          default = {
            type = "app";
            program = "${fpcc}/bin/fpcc";
          };
          precisa = {
            type = "app";
            program = "${precisa}/bin/precisa";
          };
        };

        devShells.default = pkgs.mkShell {
          packages = [
            # Haskell
            haskellPkgs.ghc
            stackWithSystemGhc
            pkgs.cabal-install
            pkgs.haskellPackages.hpack
            haskell-language-server
            pkgs.fourmolu
            pkgs.hlint

            # PRECiSA
            precisa

            # C/C++ build tooling from setup.sh
            pkgs.cmake
            pkgs.gnumake
            pkgs.pkg-config
            pkgs.wget
            pkgs.curl
            pkgs.git
            pkgs.zlib
            gccForLanguageC
          ];

          buildInputs = [ filib kodiak ];

          FILIB_ROOT = filib;
          KODIAK_LIB_DIR = "${kodiak}/lib";

          shellHook = ''
            export LIBRARY_PATH="${kodiak}/lib:${filib}/lib''${LIBRARY_PATH:+:$LIBRARY_PATH}"
            export LD_LIBRARY_PATH="${kodiak}/lib:${filib}/lib''${LD_LIBRARY_PATH:+:$LD_LIBRARY_PATH}"
          '';
        };
      }
    );
}
